### ISSUE TITLE
How can I register without invitation?

### ISSUE THREAD

**Issue by mattiaz9** [GetLoginEth/login#8]
I tried to get the contract address at this link: https://swarm-gateways.net/bzz:/getlogin.eth/xsettings but it redirects to the dapp.

Am I doing something wrong?

**Comment by IgorShadurin** [comment]
Hey. Currently you can register only with invite. You can use this: 1fea306cb6769d7a03b8922b5d50daf57bb455e9ccc7d94cfbad541f31a1c263

**Comment by IgorShadurin** [comment]
Also you can try this demo app https://swarm-gateways.net/bzz:/2e58dc766e1f9dc720369072d5cc636f8895bbed665d670aeb380ac3118f83ec/
